disableKinds:
  - taxonomy
theme:
  - scientific-python-hugo-theme/themes/hugo-atom-layout
params:
  colorScheme: auto # can be auto (browser setting), light, or dark
  images:
    - /images/logo.svg
  navColor: blue
  search: false
  plausible:
    script: null
