name: Labels

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [reopened, labeled, unlabeled]

env:
  LABELS: ${{ join( github.event.pull_request.labels.*.name, ' ' ) }}

jobs:
  check-type-label:
    name: ensure type label
    runs-on: ubuntu-latest
    steps:
      - if: "contains( env.LABELS, 'type: ' ) == false"
        run: exit 1
